# /etc/rsyslog.d/50-forward-to-voltron.conf
# Place this file on EACH REMOTE HOST (tekaden, zura).
# Forwards all logs to voltron over TCP for reliability.

# Forward everything to the central log server
*.* action(
    type="omfwd"
    target="192.168.1.129"
    port="514"
    protocol="tcp"
    action.resumeRetryCount="10"
    queue.type="linkedList"
    queue.size="10000"
    queue.filename="fwd_to_voltron"
    queue.saveOnShutdown="on"
)
